### PR TITLE
5.1.1_r28 --> 5.1.1_r37

### PR DESCRIPTION
**Pull request by Startrek852**

### CODE REVIEW

**Comment by lj50036** [comment]
This one we are going to have to talk about....

It would be best if you could join irc.....

**Comment by Startrek852** [comment]
OK, I have an IRC client installed and setup. What server/channel do you want me to join?

**Comment by lj50036** [comment]
Network: freenode
Channel: #twrp

**Comment by Startrek852** [comment]
Hey, I joined the channel, but you're idle.

**Pull request closed without merging**
